inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

