---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/samples":
    get:
      summary: Lists samples
      tags:
      - Samples
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
